webserver:
  port: 5003

static:
  prefix: '/public'

redis:
  keyPrefix: 'poppy:'
  host: 106.14.147.173
  port: 6379

log4js:
  appenders:
    out:
      type: 'stdout'
  categories:
    default:
      appenders:
        - 'out'
      level: 'all'
